### ISSUE TITLE
How to code for multiple output values in decision tables

### ISSUE THREAD

**Issue by marc4gov** [dmntk/dmntk.rs#47]
I have a decision table with multiple output columns, but I can't manage to get both values out of it, using variable name `params`
[Multiple_output.zip](https://github.com/dmntk/dmntk.rs/files/11529072/Multiple_output.zip)

**Comment by dmntk** [comment]
Hi,

Firstly I have checked the input data types and corrected the **aow** variable (was _number_ instead of _boolean_):
```
<inputData id="InputData_1oak7a1" name="AOW">
  <variable name="aow" typeRef="boolean"/>
</inputData>
```
then it worked, I have run a command:
```
$ dmntk edm --invocable params huurtoeslag.ctx huurtoeslag.dmn
```
and the result was correct from the decision table named **params**:
```
{"factor_a": 0.1, "factor_b": 0.2}
```
When run as a service, the result was:
```
{"data":{"factor_a": 0.1, "factor_b": 0.2}}
```
I guess this was a problem - mismatched variable type in input data.

I have seen typeRefs="double" - these should be "number" and the output variable of **params** decision table has no typeRef, this is invalid, but works in current version, so I added the right type definition:
```
<decision id="Decision_0wqy94m" name="params">
        <variable name="params" typeRef="tParameters"/>
        <informationRequirement id="InformationRequirement_0gjlq3c">
...
```
Let me know if it worked for you ;-)

**Comment by marc4gov** [comment]
Thanks, worked. I keep messing up these things, would be nice if editors complied with DMN 1.3...
